"""Embed data/wage1.csv into js/sample-data.js so the site works from file:// (no fetch)."""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
csv = (root / "data" / "wage1.csv").read_text()
(root / "js" / "sample-data.js").write_text(
    "// Generated by scripts/build_sample.py from data/wage1.csv. Do not edit by hand.\n"
    f"window.SAMPLE_CSV = {json.dumps(csv)};\n"
)
print("wrote js/sample-data.js")
